# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

site_name: Common Ground Electronics Docs
site_url: https://docs.cgnd.dev
theme:
  name: material
