# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

site_name: Common Ground Electronics Docs
site_url: https://docs.cgnd.dev
copyright: Copyright &copy; Common Ground Electronics
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      accent: light-blue
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: light-blue
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon-32x32.png
  logo: assets/images/logo.svg
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
extra:
  homepage: https://cgnd.dev
extra_css:
  - assets/stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
