# SPDX-FileCopyrightText: Common Ground Electronics <https://cgnd.dev>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1
SPDX-PackageName = "docs"
SPDX-PackageSupplier = "Common Ground Electronics <https://cgnd.dev>"
SPDX-PackageDownloadLocation = "https://github.com/cgnd/docs"

[[annotations]]
path = ["**.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Common Ground Electronics <https://cgnd.dev>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [".vscode/settings.json", ".vscode/settings.default.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Common Ground Electronics <https://cgnd.dev>"
SPDX-License-Identifier = "MIT or Apache-2.0"
